spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: ecommerce
    password: ecommerce321!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    rest:
      base-path: /api